{{- $fullName := printf "%s" (include "azurite.fullname" . ) -}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    {{- include "azurite.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- if .Values.config.blobs.enabled and .Values.ingress.host.blobs }}
    - host: {{ .Values.ingress.host.blobs | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: blobs
    {{- end }}
    {{- if .Values.config.queues.enabled and .Values.ingress.host.queues }}
    - host: {{ .Values.ingress.host.queues | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: queues
    {{- end }}
    {{- if .Values.config.tables.enabled and .Values.ingress.host.tables }}
    - host: {{ .Values.ingress.host.tables | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: tables
    {{- end }}
{{- end }}
