{{- $fullName := printf "%s" (include "azurite.fullname" . ) -}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    {{- include "azurite.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if and (.Values.config.blobs.enabled) (.Values.ingress.host.blobs) }}
    - host: {{ .Values.ingress.host.blobs | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: blobs
    {{- end }}
    {{- if and (.Values.config.queues.enabled) (.Values.ingress.host.queues) }}
    - host: {{ .Values.ingress.host.queues | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: queues
    {{- end }}
    {{- if and (.Values.config.tables.enabled) (.Values.ingress.host.tables) }}
    - host: {{ .Values.ingress.host.tables | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: tables
    {{- end }}
{{- end }}
