{{- $fullName := printf "%s" (include "azurite.fullname" . ) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    {{- include "azurite.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.config.blobs.enabled }}
    - port: 10000
      targetPort: blobs
      protocol: TCP
      name: blobs
    {{- end }}
    {{- if .Values.config.queues.enabled }}
    - port: 10001
      targetPort: queues
      protocol: TCP
      name: queues
    {{- end }}
    {{- if .Values.config.tables.enabled }}
    - port: 10002
      targetPort: tables
      protocol: TCP
      name: tables
    {{- end }}
  selector:
    app: {{ $fullName }}
